AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "db/**/*"
    - "bin/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/**/*"
    - "bin/**/*"
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20